# notroot's .bashrc (Joseph Edwards VIII)

# Variables

PROMPT_WHITE="\[\033[1;37m\]"
PROMPT_GREEN="\[\033[01;32m\]"
PROMPT_CYAN="\[\033[01;36m\]"
PROMPT_GRAY="\[\033[0;37m\]"
PROMPT_BLUE="\[\033[0;34m\]"
PROMPT_PREFIX_LONG="${PROMPT_GREEN}\u${PROMPT_CYAN}@${PROMPT_BLUE}\h "
PROMPT_PREFIX_SHORT="${PROMPT_GREEN}\u${PROMPT_CYAN}:"

PS1_XS="PS1='\n${debian_chroot:+($debian_chroot)}${PROMPT_PREFIX_SHORT}${PROMPT_CYAN}\W${PROMPT_GRAY}:\$ '"
PS1_S="PS1='\n${debian_chroot:+($debian_chroot)}${PROMPT_PREFIX_SHORT}${PROMPT_CYAN}\W${PROMPT_GRAY} \$ '"
PS1_L="PS1='\n${debian_chroot:+($debian_chroot)}${PROMPT_PREFIX_SHORT}${PROMPT_CYAN}\w${PROMPT_GRAY} \$ '"
PS1_XL="PS1='\n${debian_chroot:+($debian_chroot)}${PROMPT_PREFIX_SHORT}${PROMPT_CYAN}\w${PROMPT_GRAY} 
\$ '"

# Set default locale
# export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# set default editor
export EDITOR="emacs -nw"

# For older GTK & QT appz
export GDK_USE_XFT=1
export QT_XFT=true

# some roots
export BOOST_ROOT=/usr/local/boost_1_53_0

SAGE_ROOT=/opt/sage
PATH=$PATH:$SAGE_ROOT
export PATH
export SAGE_MATPLOTLIB_GUI=yes
export SAGE_BROWSER="chromium"

ANDROID_TOOLS=/opt/android-sdk/tools
PATH=$PATH:$ANDROID_TOOLS
export PATH

export GPGKEY=D7E1D3C8

##### Aliases

alias ps1_s=$PS1_S
alias ps1_l=$PS1_L
alias ps1_xs=$PS1_XS
alias ps1_xl=$PS1_XL

# general mods
alias ls="ls --color=auto "
alias ll="ls -alF"
alias h="history|grep "
alias f="find . |grep "
alias p="ps aux |grep "
#alias o="gnome-open "

#thx E. Rouat
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias ..='cd ..'
alias path='echo -e ${PATH//:/\\n}'

# These r mine
alias emax="emacs -nw "
alias semac="sudo emacs -nw "
alias edrc="sudo emacs -nw ~/.bashrc"
#alias agi="sudo apt-get install "
#alias matlab="matlab -glnx86"
#alias py="python "

alias fixconky="killall -SIGUSR1 conky"
alias fixwm="xfwm4 --replace"

##### Misc. functions

function cdl { cd $1; ls; }
function cpf { cp $1 $2; cdl $2; }
function mvf { mv $1 $2; cdl $2; } 

# archlinux mirrors
function reflect {
    sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
    reflector -l $1 -c 'United States' -p http --sort rate --save /etc/pacman.d/mirrorlist
    cat /etc/pacman.d/mirrorlist
}

# netctl shortcuts
function snetctl {
    local cmd=""

    if [ $# = 2 ]; then
	cmd="$1"
	prof="$2"
    else
	cmd="start"
	prof="$1"
    fi

    sudo netctl stop-all
    sudo netctl $cmd $prof
}

function batnet {
    if [ $# = 0 ]; then
	$1="on"
    fi

    if [ "$1" = "on" ]; then
        snetctl start batcomputer
    else
	snetctl stop batcomputer
    fi
}

# Apache shortcuts (relies on alias 'll')
function apache {
    local fpath="/etc/apache2 "
    local bpath="/usr/sbin/apache2ctl "

    if [ $# = 0 ]; then
        cd $fpath; ll;
    else 
        sudo $bpath $@
    fi
}

# Wine functions
prefix() {
    if [ -z "$1" ]; then
        echo "${HOME}/.wine/"
    else
        echo "${HOME}/.local/share/wineprefixes/$1"
    fi
}

goc() {
    cd "$(prefix)/drive_c"
}

lsp() {
    ls $* "${HOME}/.local/share/wineprefixes"
}

run() {
    WINEPREFIX="$(prefix $1)" wine cmd /c "C:\\run-$1.bat"
}

complete -W "$(lsp)" prefix run

##### PySpace - to help collect virtualenvs into project spaces

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Dev/python/
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
#source /usr/bin/virtualenvwrapper.sh

# 'virtualenvwrapper' aliases by user at:
# http://blog.doughellmann.com/2010/01/virtualenvwrapper-tips-and-tricks.html
alias v='workon'
alias v.deactivate='deactivate'
alias v.mk='mkvirtualenv --no-site-packages'
alias v.mk_withsitepackages='mkvirtualenv'
alias v.rm='rmvirtualenv'
alias v.switch='workon'
alias v.add2virtualenv='add2virtualenv'
alias v.cdsitepackages='cdsitepackages'
alias v.cd='cdvirtualenv'
alias v.lssitepackages='lssitepackages'
function v.usage {
    printf "v=workon, v.deactivate, v.mk, v.mk_withsitepackages, v.rm, v.switch\nv.add2virtualenv, v.cdsitepackages, v.cd, v.lssitepackages\n"
}

# 'pythonbrew' aliases, Joseph Edwards VIII <joseph8th@urcomics.com>
[[ -s "$HOME/.pythonbrew/etc/bashrc" ]] && source "$HOME/.pythonbrew/etc/bashrc"

alias pb='pythonbrew'
alias pb.ls='pb list'
alias pb.get='pb install '
alias pb.use='pb use '
alias pb.switch='pb switch '
alias pb.ln='pb symlink '
alias pb.clean='pb cleanup'

alias pb.v='pb venv'
alias pb.v.ls='pb.v list'
alias pb.v.mk='pb.v create '
alias pb.v.mv='pb.v rename '
alias pb.v.rm='pb.v delete '
alias pb.v.lpact='pb.v print_activate'

#### Last things last...
ps1_l

### Pybrat pythonbrew commander and virtualenv wrangler ###
[[ -s "$HOME/.pybrat/etc/bashrc" ]] && source "$HOME/.pybrat/etc/bashrc"

alias pv='pybrat '
alias pv.ls='pybrat list '
alias pv.init='pybrat init '
alias pv.mk='pybrat mk '
alias pv.rm='pybrat rm '
alias pv.use='pybrat use '

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting


# 'pyenv' environment configuration
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
